# Generated by Django 4.1.1 on 2022-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=200, verbose_name='автор'),
            preserve_default=False,
        ),
    ]
